---

version: '3.7'

services:
  app:
    image: app:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
    networks:
      - webnet

networks:
  webnet:
